"""Fix delivery status enum

Revision ID: 1721b063d128
Revises: 9b7bceca0c4c
Create Date: 2025-04-26 14:04:23.458854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1721b063d128'
down_revision = '9b7bceca0c4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delivery_logs_retention', table_name='delivery_logs')
    op.drop_index('ix_delivery_logs_retry_status_time', table_name='delivery_logs', postgresql_where="((status = 'pending'::deliverystatus) AND (next_retry_at IS NOT NULL))")
    op.drop_index('ix_delivery_logs_subscription_status', table_name='delivery_logs')
    op.drop_index('ix_delivery_logs_webhook_attempt', table_name='delivery_logs')
    op.create_index(op.f('ix_delivery_logs_id'), 'delivery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_delivery_logs_id'), table_name='delivery_logs')
    op.create_index('ix_delivery_logs_webhook_attempt', 'delivery_logs', ['webhook_id', 'attempt_number'], unique=False)
    op.create_index('ix_delivery_logs_subscription_status', 'delivery_logs', ['subscription_id', 'status'], unique=False)
    op.create_index('ix_delivery_logs_retry_status_time', 'delivery_logs', ['status', 'next_retry_at'], unique=False, postgresql_where="((status = 'pending'::deliverystatus) AND (next_retry_at IS NOT NULL))")
    op.create_index('ix_delivery_logs_retention', 'delivery_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###