"""Make secret_key mandatory in subscriptions

Revision ID: bdc59a84bcc6
Revises: 2023b063d129
Create Date: 2025-04-27 04:45:06.311545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = 'bdc59a84bcc6'
down_revision = '2023b063d129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First update any existing subscriptions that have NULL secret_key
    # to give them a default random value before making the column non-nullable
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            UPDATE subscriptions 
            SET secret_key = 'generated_' || gen_random_uuid() 
            WHERE secret_key IS NULL
            """
        )
    )
    
    # Now make the column non-nullable
    op.drop_index('ix_delivery_logs_retention', table_name='delivery_logs')
    op.drop_index('ix_delivery_logs_retry_status_time', table_name='delivery_logs', postgresql_where="((status = 'pending'::deliverystatus) AND (next_retry_at IS NOT NULL))")
    op.drop_index('ix_delivery_logs_subscription_status', table_name='delivery_logs')
    op.drop_index('ix_delivery_logs_webhook_attempt', table_name='delivery_logs')
    op.alter_column('subscriptions', 'secret_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('webhooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhooks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_webhooks_id', table_name='webhooks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_webhooks_id', 'webhooks', ['id'], unique=False)
    op.alter_column('webhooks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhooks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'secret_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_delivery_logs_webhook_attempt', 'delivery_logs', ['webhook_id', 'attempt_number'], unique=False)
    op.create_index('ix_delivery_logs_subscription_status', 'delivery_logs', ['subscription_id', 'status'], unique=False)
    op.create_index('ix_delivery_logs_retry_status_time', 'delivery_logs', ['status', 'next_retry_at'], unique=False, postgresql_where="((status = 'pending'::deliverystatus) AND (next_retry_at IS NOT NULL))")
    op.create_index('ix_delivery_logs_retention', 'delivery_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###